### ISSUE TITLE
choose fair peer busy and idle

### ISSUE THREAD

**Issue by haonhien** [gnosek/nginx-upstream-fair#9]
2 ways to choose a best peer, but I'm having some problems as my peer connection was full due to slow response time, so I have some idea, is to choose the best peer-based on two factors:
- response time of peer, if the peer does have the fastest response time, then select the best peer.
- The number of error messages returned (400,404,500). If any peer returns an error message at least choose the best peer.

Plase. help me.
If possible, please guide me how to write ideas on.

**Comment by gnosek** [comment]
Peer scoring is done in ngx_http_upstream_fair_sched_score():

https://github.com/gnosek/nginx-upstream-fair/blob/master/ngx_http_upstream_fair_module.c#L688

Write your logic there, though you'll probably need to adapt ngx_http_upstream_get_fair_peer() and ngx_http_upstream_free_fair_peer() to collect relevant statistics. You'll probably want an exponential weighted moving average to store the response time with low overhead and something similar that gives less weight to old data for the error counter so that a backend having issues in the past isn't penalised too much.
